# Generated by Django 5.2.8 on 2025-11-30 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('textbooks', 'Textbooks'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('supplies', 'Supplies'), ('sports', 'Sports & Outdoors'), ('other', 'Other')], max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('used', 'Used')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('draft', 'Draft')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_listing',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'status'], name='product_lis_categor_69e947_idx'), models.Index(fields=['seller', 'status'], name='product_lis_seller__eeffb3_idx')],
            },
        ),
    ]
